#!/usr/bin/env zsh

# ==========================================================
# brew_force
# Fri Oct  2 00:18:21 2020
# AUTHOR: solarizedalias
#
# ==========================================================

emulate -R zsh
setopt typeset_silent no_short_loops no_auto_pushd
setopt extended_glob  glob_dots      rc_quotes      hist_subst_pattern

readonly SOURCE="${${(%):-%N}:a}"
readonly NAME="${SOURCE:t}"
readonly HEAD="${SOURCE:h}"

(
  command brew unlet && command brew update-reset && command brew let
) &!

