#!/usr/bin/env zsh
# vim:ft=zsh:

# ==========================================================
# scapegoat
# Tue Sep 22 21:42:10 2020
# AUTHOR: solarizedalias
#
# ==========================================================

emulate -R zsh
setopt typeset_silent no_short_loops no_auto_pushd
setopt extended_glob  glob_dots      rc_quotes      hist_subst_pattern

readonly SOURCE="${${(%):-%N}:a}"
readonly NAME="${SOURCE:t}"
readonly HEAD="${SOURCE:h}"

local -A Goats
for c in {0..9} {A..Z} {a..z} {-,/,_,\~,.}; do
  Goats+=( [$(( #c ))]="$c" )
done

function Staog() {
  local Rhymer
  for p in ${(@M)@:#<->}; do
    Rhymer+="${Goats[$p]}"
  done
  builtin print -lr -- ${Rhymer}
}

readonly DWARF="$(Staog 47 85 115 101 114 115 47 121 107 107 115 100 47 100 111 116 102 105 108 101 115 )"
readonly QBERT="${:-${DWARF}}"

pushd -q ${QBERT}
rat "$(Staog 46 101 110 118)"
popd -q

