#!/usr/bin/env zsh

emulate -LR zsh
setopt extended_glob  glob_dots      rc_quotes      hist_subst_pattern
setopt typeset_silent no_short_loops no_auto_pushd
setopt noclobber      noappendcreate
setopt warn_create_global
setopt errexit nounset

function echo_run() {
  printf '%s\n' "${(j: :)@}"
  $@
}

echo_run git fetch --prune

echo_run git branch -vv | \
  grep ': gone]' | \
  awk '{print $1}' | \
  xargs -t -r git branch -d

