#!/usr/bin/env zsh

emulate -LR zsh
setopt warn_create_global typeset_silent no_short_loops no_auto_pushd
setopt extended_glob      glob_dots      rc_quotes      hist_subst_pattern
setopt NO_clobber NO_append_create

local -a instances
instances=( ${(f)"$(pgrep zsh)"} )
print -r -- ${#instances}

