import = [
  "~/.config/alacritty/mythemes/base.toml",
  # "~/.config/alacritty/themes/themes/xterm.toml",
  # "~/.config/alacritty/themes/themes/blood_moon.toml",
  # "~/.config/alacritty/themes/themes/campbell.toml",
]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#3f7ed6"
text = "CellBackground"

[colors.normal]
# black   = "#000000"
# blue    = "#24a6fa"
# cyan    = "#54ced6"
# green   = "#b9fa4a"
magenta = "#f77ee0"
# red     = "#fe4e33"
# white   = "#eaeaea"
# yellow  = "#e6c547"

# [colors.bright]
# black   = "#666666"
# blue    = "#7aa6da"
# cyan    = "#84ced6"
# green   = "#9ef4a0"
# magenta = "#ffc7e8"
# red     = "#ff6334"
# white   = "#ffffff"
# yellow  = "#eff547"

# [colors.dim]
# black   = "#000000"
# blue    = "#506d8f"
# cyan    = "#497e7a"
# green   = "#7a8530"
# magenta = "#80638e"
# red     = "#8c3336"
# white   = "#9a9a9a"
# yellow  = "#97822e"


[colors.primary]
background        = "#000000"
foreground        = "#eaeaea"
bright_foreground = "#ffffff"
dim_foreground    = "#9a9a9a"


[window]
decorations = "none"
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"
# option_as_alt = "OnlyLeft"

[bell]
animation = "Ease"
duration = 50
color = "#111111"

[cursor]
blink_interval = 500
blink_timeout = 0
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"


[font]
size = 12.0
[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
chars = '\'
key = "¥"

[[keyboard.bindings]]
chars = "¥"
key = "¥"
mods = "Option"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "C"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control"


[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

